import angular from 'angular';
import 'angular-ui-router';

// import config files
import constants from './config/constants';
import config from './config/config';
import run from './config/run';



//import templates file, generated by Gulp task
import './config/templates';
import './layout';
import './components';
import './home';
import './profile';
import './article';
import './services';
import './auth';

//create and bootstrap app

const requires = [
    'ui.router',
    'templates',
    'app.layout',
    'app.components',
    'app.home',
    'app.profile',
    'app.article',
    'app.services',
    'app.auth'
];

window.app = angular.module('app', requires);

angular.module('app')
    .constant('AppConstants', constants)
    .config(config)
    .run(run);

angular.bootstrap(document, ['app'], {
    strictDi: true
});